/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Person } from "./Person";
import { PersonFindManyArgs } from "./PersonFindManyArgs";
import { PersonService } from "../person.service";
@graphql.Resolver(() => Person)
export class PersonResolverBase {
  constructor(protected readonly service: PersonService) {}

  @graphql.Query(() => [Person])
  async people(@graphql.Args() args: PersonFindManyArgs): Promise<Person[]> {
    return this.service.people(args);
  }
}
